### ISSUE TITLE
Set-up Docs

### ISSUE THREAD

**Issue by debraj-manna** [vikingco/django-kong-admin#3]
Is there any doc that can be referred for setting up `kong-admin`?

**Comment by dirkmoors** [comment]
Hello,

As of yet there is no documentation.

The steps you need to take are:

```bash
pip install django-kong-admin
```

In your Django Project:
```python
INSTALLED_APPS = (
    ....
    'jsonfield2',  # https://github.com/DarioGT/django-jsonfield2
    'django_ace',  # https://github.com/bradleyayers/django-ace
    'kong_admin'
    ....
)
```

In your base url patterns:
```python
urlpatterns = [
    ....
    url(r'^admin/', include(admin.site.urls)),
    ....
    # Optionally, add the following url, which is a view that displays the current kong config:
    url(r'^showconfig/', 'kong_admin.views.show_config')
    .... 
]
```

Then you can go to your Django admin site, and the Kong Admin entities will be manageable.

I plan to add more documentation in the near future! If you want to contribute to the library, be my guest!
